// Generated by https://quicktype.io

export interface Venta {
  id:           number;
  ordenVenta:   string;
  descVenta:    string;
  estadoVenta:  EstadoVenta;
  fechaReserva: string;
  cliente:      Cliente;
  factura:      Factura;
  user:         User;
}

export interface Cliente {
  id:               number;
  nombreCliente:    string;
  apellidosCliente: string;
  docId:            string;
  tipoDoc:          TipoDoc;
  estadoCliente:    EstadoCliente;
  fonoCliente:      string;
  emailCliente:     string;
}

export interface Factura {
  id:         number;
  codFactura: string;
  formaPago:  FormaPago;
  fechaPago:  string;
  producto:   Producto;
}

export interface Producto {
  id:             number;
  nombreProducto: string;
  descProducto:   string;
  precioProducto: number;
}

export interface User {
  id:                    number;
  username:              string;
  password:              string;
  email:                 string;
  name:                  string;
  lastName:              string;
  role:                  Role;
  enabled:               boolean;
  authorities:           Authority[];
  accountNonExpired:     boolean;
  credentialsNonExpired: boolean;
  accountNonLocked:      boolean;
}

// enums

export interface Authority {
  authority: string;
}

export enum EstadoCliente {
  INTERESADO = "INTERESADO",
  CLIENTE = "CLIENTE"
}

export enum EstadoVenta {
  LEAD = "LEAD",
  CONTACTO = "CONTACTO",
  PRESENTAR_PRODUCTO = "PRESENTAR_PRODUCTO",
  PROPUESTA = "PROPUESTA",
  NEGOCIACION = "NEGOCIACION",
  EN_PROCESO = "EN_PROCESO",
  CIERRE_PERDIDA = "CIERRE_PERDIDA",
  CIERRE_GANADO = "CIERRE_GANADO"
}

export enum FormaPago {
  EFECTIVO = "EFECTIVO",
  TARJETA = "TARJETA",
  OTRO = "OTRO"
}

export enum Role {
  USER = "USER",
  ADMINISTRATOR = "ADMINISTRATOR"
}

export enum TipoDoc {
  DNI = "DNI",
  CE = "CE",
  RUC = "RUC",
  PASAPORTE = "PASAPORTE"
}

export enum AuthStatus {
  checking         = 'checking',
  authenticated    = 'authenticated',
  notAuthenticated = 'notAuthenticated',
}
